import type { Metadata } from "next";
import { Toaster } from "react-hot-toast";
import Header from "@/components/Header";

import { AuthProvider } from "@/features/auth/AuthContext";
import "./globals.css";

export const metadata: Metadata = {
  title: "Booking App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex min-h-full flex-col">
        <AuthProvider>
          <Header />
          <main className="mx-auto w-full max-w-5xl flex-1 p-4">
            <Toaster position="top-center" toastOptions={{ style: { fontSize: "1.4rem" }, closeButton: true }} />
            {children}
          </main>
        </AuthProvider>
      </body>
    </html>
  );
}
